AllCops:
  TargetRubyVersion: 2.3.0
  TargetRailsVersion: 5
  Exclude:
   - 'node_modules/**/*'
   - 'vendor/**/*'
   - 'config/**/*'
   - 'db/**/*'
   - 'bin/**/*'

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'db/migrate/**/*.rb'
    - 'db/data/**/*.rb'
    - 'lib/tasks/**/*.rake'
    - 'config/**/*.rb'

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Style/AsciiComments:
  Enabled: false